apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
  labels:
    name: monitoring
---
apiVersion: v1
kind: Service
metadata:
  name: grafana
spec:
  type: NodePort
  selector:
    app: grafana
  ports:
  - name: grafana
    port: 3000
    targetPort: 3000
    nodePort: 30300
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      name: grafana
      labels:
        app: grafana
    spec:
      containers:
      - name: grafana
        image: grafana/grafana:6.2.5
        ports:
        - containerPort: 3000
        # command: ["chown", "-R", "472:472", "/efs/grafana/data/"]
        env:
        - name: TZ
          value: Asia/Tokyo
        - name: GF_PATHS_HOME
          value: /usr/share/grafana
        - name: GF_PATHS_DATA
          value: /efs/grafana/data
        - name: GF_PATHS_LOGS
          value: /var/log/grafana
        - name: GF_PATHS_PLUGINS
          value: /efs/grafana/plugins
        - name: GF_PATHS_PROVISIONING
          value: /etc/grafana/provisioning
        volumeMounts:
        - name: config
          mountPath: /etc/grafana
        - name: data-volume
          mountPath: /efs/
      securityContext:
        runAsUser: 0
        fsGroup: 1000
      volumes:
      - name: config
        configMap:
          name: grafana-config
      - name: data-volume
        persistentVolumeClaim:
              claimName: prometheus-pvc