apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
  labels:
    name: monitoring
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus
  # namespace: monitoring
spec:
  type: NodePort
  selector:
    app: prometheus
  ports:
  - name: prometheus
    port: 9090
    targetPort: 9090
    nodePort: 30090
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: prometheus
  # namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      name: prometheus
      labels:
        app: prometheus
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: '9090'
        prometheus.io/path: /metrics
    spec:
      containers:
      - name: prometheus
        image: prom/prometheus:v2.10.0
        args: [ "--storage.tsdb.path=/mnt/", "--config.file=/mnt/etc/prometheus.yml", "--storage.tsdb.no-lockfile" ]
        ports:
        - containerPort: 9090
        volumeMounts:
        - name: config
          mountPath: /mnt/etc/
        - name: data-volume
          mountPath: /mnt/
      securityContext:
        runAsUser: 0
        fsGroup: 2000
      volumes:
      - name: config
        configMap:
          name: prometheus-config
      - name: data-volume
        persistentVolumeClaim:
              claimName: prometheus-pvc