apiVersion: v1
kind: Service
metadata:
  name: grafana-loki
spec:
  type: NodePort
  selector:
    app: grafana-loki
  ports:
  - name: grafana-loki
    port: 3100
    targetPort: 3100
    nodePort: 30500
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: grafana-loki
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana-loki
  template:
    metadata:
      name: grafana-loki
      labels:
        app: grafana-loki
    spec:
      containers:
      - name: grafana-loki
        image: grafana/loki:master
        args: ["-config.file=/etc/loki/local-config.yaml"]
        ports:
        - containerPort: 3100
        volumeMounts:
        - name: config
          mountPath: /etc/loki
        - name: data-volume
          mountPath: /efs/
      securityContext:
        runAsUser: 0
        fsGroup: 1000
      volumes:
      - name: config
        configMap:
          name: grafana-loki-config
      - name: data-volume
        persistentVolumeClaim:
              claimName: prometheus-pvc