apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cassandra-data
spec:
  storageClassName: awsebs
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 30Gi